service: frontend-pay-360hub

params:
  dev:
    domain: pay-dev.360h.com.br
    cert: arn:aws:acm:us-east-1:974609723172:certificate/9c593178-bcdc-4cc0-b218-0e99fa138a99
    hosted-zone-id: Z03920093G2NCHPXWKWQ0
    raw-domain: 360h.com.br
  
  staging:
    domain: pay-staging.360h.com.br
    cert: arn:aws:acm:us-east-1:974609723172:certificate/9c593178-bcdc-4cc0-b218-0e99fa138a99
    hosted-zone-id: Z03920093G2NCHPXWKWQ0
    raw-domain: 360h.com.br

  prod:
    domain: pay.360h.com.br
    cert: arn:aws:acm:us-east-1:974609723172:certificate/9c593178-bcdc-4cc0-b218-0e99fa138a99
    hosted-zone-id: Z03920093G2NCHPXWKWQ0
    raw-domain: 360h.com.br

plugins:
  - serverless-offline
  - serverless-s3-sync
  - serverless-plugin-common-excludes
  - serverless-cloudfront-invalidate

provider:
  name: aws
  runtime: nodejs20.x
  stage: '${opt:stage,''dev''}'
  region: ${opt:region, env:REGION, 'us-east-1'}
  timeout: 300

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    #- test/**
    - src/**
    #- README.md
    #- .env*
    - package-lock.json
    - yarn.lock

custom:
  bucketName: 'pay-360hub-${opt:stage,''dev''}'
  cloudfrontInvalidate:
    - distributionIdKey: CDNDistributionId
      items:
        - "/*"
  s3Sync:
    - bucketName: 'pay-360hub-${opt:stage,''dev''}'
      localDir: dist/
  domainName: ${param:domain}
  domainCertArn: ${param:cert}
  hostedZoneId: ${param:hosted-zone-id}
  rawDomain: ${param:raw-domain}

resources:
  - ${file(resources/serverless/s3.yml)}
  - ${file(resources/serverless/cloudfront.yml)}
  - ${file(resources/serverless/route53.yml)}
  - Outputs:
      CDNDistributionId:
        Description: Distribution ID.
        Value:
          Ref: CloudFrontDistribution
