Resources:
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: ${self:custom.domainName}
      HostedZoneName: ${self:custom.rawDomain}.
      Type: 'A'
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - CloudFrontDistribution
            - DomainName
        HostedZoneId: ${self:custom.hostedZoneId}